### ISSUE TITLE
How to remove the Label Fields name and Value Fields name in tooltip and legend

### ISSUE THREAD

**Issue by auntieyi** [meln5674/grafana-mongodb-community-plugin#10]
Hi,

My options as below:
```
Label Fields: productName
Value Fields: price
```

The tooltip and legend are showing the Label Fields name and Value Fields name like this:
```
productName=AAAA price 123
productName=BBBB price 345
```

How can make it showing as following?
```
AAAA 123
BBBB 345
```

**Comment by meln5674** [comment]
I think the Legend Format will do what you're looking for, try setting
```
Legend Format: {{ .Labels.productName }}
```

**Comment by auntieyi** [comment]
I works with v0.2.0+rc3, thank you!
