### ISSUE TITLE
An unexpected error happened

### ISSUE THREAD

**Issue by ddoice** [meln5674/grafana-mongodb-community-plugin#18]
Hi there!

I'm trying to use this great plugin with no luck, as soon as I try to use it as a data source this error appeears on the UI:

![image](https://user-images.githubusercontent.com/14946058/236622241-3b824519-e4cc-4b6f-9eb3-c0981195f850.png)

Do you have any idea why this might happen?

- Grafana version 6.7.3.
- Using the zip release version v0.2.0+rc3

**Comment by meln5674** [comment]
Grafana 6.X is quite old at this point (more than 3 years), and I know somewhere in there Grafana re-wrote their plugin framework, so its entirely possible that the newer plugin framework isn't compatible with older versions. The integration tests are run against the latest stable version line (9.X),  but I will see if I can get it running against older versions as well.

**Comment by meln5674** [comment]
After having done some digging, I regret to inform you that this plugin is, in fact, incompatible with Grafana 6. In Grafana 7, the version of React.js was upgraded from the legacy version that used plain JavaScript to the modern version that uses TypeScript. Further, the plugin uses UI components that were added in Grafana 9. If you wish to use this plugin, you will need to upgrade your Grafana installation.

**Comment by ddoice** [comment]
I really appreciate it!
I will try to upgrade Grafana.
