### ISSUE TITLE
Access the date picker of Grafana

### ISSUE THREAD

**Issue by Kromtar** [meln5674/grafana-mongodb-community-plugin#19]
Is there any way to incorporate the selected date range from Grafana's date picker into the aggregation query?

**Comment by meln5674** [comment]
Yes, the start and end dates are provided as the `$__from` and `$__to` variables which can be included in your query, as described [here](https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#__from-and-__to) . As well, if you use the timeseries query type, there is an option to automatically inject a `$match` stage before your pipeline which uses these variables, assuming your timestamp is a standard ISODate() object.

**Comment by Kromtar** [comment]
Thank very much. 

Here is an example of how to retrieve documents within a time range using Grafana's Picker.
Assume that the 'timestamp' field is where we store the time record in Date format:

```

[{
  "$match":{
    "$expr":{
      "$and":[
        {"$gte":["$timestamp",{"$toDate":"${__from:date}"}]},
        {"$lte":["$timestamp",{"$toDate":"${__to:date}"}]}
      ]
    }
  }
}]

```
