### ISSUE TITLE
Could u show some simple way to install and use on windows plz, like just docker run ...

### ISSUE THREAD

**Issue by Snakebinp** [meln5674/grafana-mongodb-community-plugin#2]

**Comment by meln5674** [comment]
Installing on windows/docker is no different to any other non-kubernetes install. If you have a running grafana instance, you can install using the [grafana-cli tool](https://grafana.com/docs/grafana/latest/cli/#override-default-plugin-zip-url) (Make sure to [enable this as an unsigned plugin](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#allow_loading_unsigned_plugins) first)

```ini
; grafana.ini
[plugins]
allow_loading_unsigned_plugins = meln5674-mongodb-community
```

```bash
grafana-cli \
  --pluginUrl https://github.com/meln5674/grafana-mongodb-community-plugin/releases/download/v0.1.0/meln5674-mongodb-community.zip \
  plugins install meln5674-mongodb-community.
```
and then restart Grafana.

If you want to do this in docker, you just need to `docker exec` into your running container before doing the above, and then `docker restart` your container.

**Comment by meln5674** [comment]
README how has copy-pasteable examples for running in both Docker and Kubernetes.
