### ISSUE TITLE
Not able to use Grafana variable in the collection field

### ISSUE THREAD

**Issue by BbBaboo42** [meln5674/grafana-mongodb-community-plugin#31]
I created a grafana variable named collection.
In my panel I tried putting $collection in the collection field but it does not work.
From inspecting the query it seems like it takes it as is (i.e "$collection").
What can I do?

This works:
![image](https://github.com/meln5674/grafana-mongodb-community-plugin/assets/162128810/f7ebf223-721c-44d8-8593-a829e5ec6532)

But this do not:
![image](https://github.com/meln5674/grafana-mongodb-community-plugin/assets/162128810/cf686ca5-3185-4dae-bfda-cdf42e6daf3a)

Grafana v10.3.1
Plugin version: 0.2.0

**Comment by BbBaboo42** [comment]
I also tried ${collection} but it did not work either

**Comment by meln5674** [comment]
The collection and database name fields currently don't support variables. I will look into supporting this later this week.

**Comment by BbBaboo42** [comment]
Wow if you could that be so amazing! It will make my dashboards extremely powerful! Thank you very much!

**Comment by meln5674** [comment]
Please try v0.2.0+rc5 which now supports variables in the database and collection fields.

**Comment by BbBaboo42** [comment]
OMG Thank you it works perfectly!
