### ISSUE TITLE
Bad document: interface conversion: interface {} is nil

### ISSUE THREAD

**Issue by seasoncool** [meln5674/grafana-mongodb-community-plugin#4]
Hi @meln5674 , please tell me what type should be input here ?

![image](https://user-images.githubusercontent.com/6467295/190342790-8442c1e3-b227-41f6-9058-80ebd7f8a0f7.png)

**Comment by meln5674** [comment]
I would recommend placing your mouse over the (i) icons next to each of the fields, they document what each field does. If these are confusing or don't explain well enough, let me know and I'll try and come up with better ones.

The "value fields" is a set of fields that are expected in each of your documents, separated by commas. So if you want to plot/show the "foo", "bar", and "baz" fields in your documents, then the value fields would be set to "foo,bar,baz" (no quotes). The "value field types" are the types of those fields, again separated by commas, in the same order. Grafana requires all data in a column to be the same type, and the plugin is still quite primitive, so you have to tell it what the type of each column is in order for it to be able to parse it. You can see the list of types here: https://pkg.go.dev/github.com/grafana/grafana-plugin-sdk-go/data#FieldType, e.g. int8 for an 8-byte signed integer, uint8 for an 8-bit unsigned integer, float64 for a 64-bit float, and adding a * in front makes a type "nullable" (optional), so *int64 means "An 64-bit signed integer that may or may not be present in all of the documents". At some point, I'll be looking into a way to have the plugin figure this out for you, but I haven't worked out a good way yet.

**Comment by seasoncool** [comment]
Hi @meln5674 , I've tried as below values which still unable to get response, could you give me an example please? Thank you.

Database: my_db
Collection: device
QueryType: Table
Value Fields: nama
Value Field Types: string
Aggregation: [{"$match" : {"device.uuid":"13afb405-5d64-42b2-8e6c-6e49620b3a53"}},{ "$project" : {"_id" : 0,"device.name":1}}]`


![image](https://user-images.githubusercontent.com/6467295/190544209-d279e83e-e8a1-4d8a-996e-eca5aa139944.png)

**Comment by meln5674** [comment]
Sure. Based on your query above, you're nearly there. If you want the "device.name" field to show up as "nama" in the grafana table, you'd just change it to
```json
[{"$match" : {"device.uuid":"13afb405-5d64-42b2-8e6c-6e49620b3a53"}},{ "$project" : {"_id" : 0,"device.name":"nama"}}]`
```
The names in "Value Fields" need to be present in the documents returned by the query, so you can either populate Value Fields from what you know will be in the result documents, or you can project the result documents to whatever you've set Value Fields to. Unfortunately, nested fields are not currently supported, but you can get around that by doing a projection like above. If you also want the device UUID to show up, you'd do something like
```
Database: my_db
Collection: device
QueryType: Table
Value Fields: nama,uuid
Value Field Types: string,string
Aggregation: [{"$match" : {"device.uuid":"13afb405-5d64-42b2-8e6c-6e49620b3a53"}},{ "$project" : {"_id" : 0,"device.name":"nama","device.uuid":"uuid"}}]
```

You can also check out the examples used in the automated tests.

https://github.com/meln5674/grafana-mongodb-community-plugin/blob/v0.1.1%2Brc1/integration-test/datasets/weather.js and https://github.com/meln5674/grafana-mongodb-community-plugin/tree/v0.1.1%2Brc1/integration-test/queries/weather are directly based on the official docs at https://www.mongodb.com/docs/manual/core/timeseries/timeseries-procedures/.

https://github.com/meln5674/grafana-mongodb-community-plugin/blob/v0.1.1%2Brc1/integration-test/datasets/tweets.sh downloads a dataset from https://github.com/ozlerhakan/mongodb-json-files/blob/master/datasets/tweets.zip, and it has its corresponding example queries at https://github.com/meln5674/grafana-mongodb-community-plugin/tree/v0.1.1%2Brc1/integration-test/queries/tweets

**Comment by seasoncool** [comment]
Hi @meln5674 , I noticed that i typed the wrong word :  "nama" should be  "name"， sorry .
 
I'v tested below cases and still no luck, please help me to fix it.

case 0 :  single field

![image](https://user-images.githubusercontent.com/6467295/190937336-bdbb3f33-522b-46ef-b789-dba5b8dd78d0.png)

case 1 :  two fields to show name & uuid only

![image](https://user-images.githubusercontent.com/6467295/190937381-800b06bd-fa52-448b-8a07-ac426510c919.png)

case 2 : two fields with "name" and "uuid" 

![image](https://user-images.githubusercontent.com/6467295/190937425-86b6a0f9-4162-4312-855b-98216014072a.png)

case 3 : two fields with parameters for "name" and "uuid"

![image](https://user-images.githubusercontent.com/6467295/190937492-8e0920f7-dc81-41a5-8f59-8c16ff73c022.png)

case 4 : import "weather" database 

![image](https://user-images.githubusercontent.com/6467295/190937967-bd44b667-6b56-4d98-8e06-db2b1a551ba3.png)


I guess that i problem might be data type however i tested each types according to grafana official :(

**Comment by meln5674** [comment]
My apologies, I seem to have given you bad information the first time. The final pipeline stage should look like this.
`{ "$project": { "name": "$device.name", "uuid": "$device.uuid" } }`
I had the order of new/old field names backwards.

Also, for case 4, that file itself isn't the aggregation, but each field in the top-level object correseponds to one of the fields in the query interface, e.g. "valueFields" in the query json file corresponds to the "Value Fields" section in the UI.

**Comment by seasoncool** [comment]
Hi @meln5674 , I'v got the result according to your last comment, thanks so much ...

![image](https://user-images.githubusercontent.com/6467295/191140161-188ea156-885d-4a40-bbc6-3da8f0dc5dc5.png)
