### ISSUE TITLE
How to setup template variable service with mongodb-community

### ISSUE THREAD

**Issue by seasoncool** [meln5674/grafana-mongodb-community-plugin#6]
hi @meln5674 ,

We are trying to setup variable with plugin however the error pops up as below image.
In fact , the related field values are worked fine with table panel, i'm not sure current release supports this feature yet.
please let me know, thanks in advance.

![image](https://user-images.githubusercontent.com/6467295/191668790-7bcb9232-a997-4a53-b4f8-6fc6896c6218.png)

**Comment by meln5674** [comment]
Sorry for the delayed response. I haven't been able to reproduce this. Can you provide the version of grafana you're using? Could you also check the javascript console for the web page and see if there are any errors listed there? This should be supported, and you can see it in this example dashboard: https://github.com/meln5674/grafana-mongodb-community-plugin/blob/master/integration-test/dashboards/retweets.json .

**Comment by meln5674** [comment]
I haven't heard back from you, so I'll be closing this issue. If this issue persists with the newer versions, please re-open and provide the version of Grafana or the container image you are running.
