### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by rajeshggwp** [meln5674/grafana-mongodb-community-plugin#8]
support SSL mode when connecting to mongodb

**Comment by meln5674** [comment]
Working on it

**Comment by rajeshggwp** [comment]
Thank you @meln5674! let me know if you need help with testing

**Comment by meln5674** [comment]
I've created [this release candidate](https://github.com/meln5674/grafana-mongodb-community-plugin/releases/tag/v0.1.2%2Brc2). I've done some tests against some dummy DB's, but if you could confirm it works in your environment, that'd be appreciated.

**Comment by rajeshggwp** [comment]
This was really quick! I'm able to connect to mongodb with SSL however TLS CA field(textbox) does not let me type or copy paste any values in it.

**Comment by meln5674** [comment]
Huh. That's what I get for doing all automated tests with pre-provisioned datasources. I'll try and figure out why that's happening. In the meantime, check [here](https://github.com/meln5674/grafana-mongodb-community-plugin/blob/master/integration-test/datasources.yaml) for examples of how to set up a datasource for it without the UI.

**Comment by meln5674** [comment]
Well, now I just feel silly. Single-character typo. I suppose that's javascript for you. New RC [here](https://github.com/meln5674/grafana-mongodb-community-plugin/releases/tag/v0.1.2%2Brc3)

**Comment by rajeshggwp** [comment]
Thanks @meln5674! I too realized it. let me quickly test this out

**Comment by rajeshggwp** [comment]
It's working now! This should be good for me to start with. When can I expect this RC to be rolled out?

**Comment by meln5674** [comment]
I generally cut a new release after [each fix](https://github.com/meln5674/grafana-mongodb-community-plugin/releases/tag/v0.1.2). I'll go ahead and close this and if you encounter any issues, go ahead and create a new issue.
