### ISSUE TITLE
Installing plugin using docker flag

### ISSUE THREAD

**Issue by dinis-rodrigues** [meln5674/grafana-mongodb-community-plugin#9]
Hello I'm trying to install the plugin using the docker flag:

```
GF_INSTALL_PLUGINS=https://github.com/meln5674/grafana-mongodb-community-plugin/releases/download/v0.1.2/meln5674-mongodb-community.zip;meln5674-mongodb-community
```

But I'm unable to find the plugin on the settings of grafana. Am I missing something?

**Comment by meln5674** [comment]
Make sure you've whitelisted the plugin, as its currently unsigned. See https://github.com/meln5674/grafana-mongodb-community-plugin/blob/master/integration-test/grafana.ini for an example. If that doesn't resolve the issue, let me know which image and tag you are using, and I'll try to reproduce the issue.

**Comment by dinis-rodrigues** [comment]
Ah cool! It worked by adding the flag:
```
GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=meln5674-mongodb-community
```

Just starting diving into grafana. Thanks! 🤙
